chore: added meeting notes for 2023-01-10
onebeyond/admin pull request #19
Opened 2023-01-10 14:40 UTC by UlisesGascon

Here are the meeting notes:

- Please review: @onebeyond/maintainers and @onebeyond/admins
- Close #18

2023-01-10 14:41 UTC, UlisesGascon commented on meetings/2023-01-10.md
> +* **Github issue:** #11
```suggestion
* **Github issue:** #18 
```

2023-01-10 14:50 UTC, inigomarquinez requested changes
Some notes added :)

2023-01-10 14:50 UTC, inigomarquinez commented on meetings/2023-01-10.md
> +* Íñigo Marquínez Prado: @inigomarquinez
* Javier Leal: @jgleal 
* Carlos Jiménez: @Betisman
* César Demicheli: @CesarD

2023-01-10 14:50 UTC, inigomarquinez commented on meetings/2023-01-10.md
> +- We will continue working to get a separate slack for open source (lead by Iñigo)
We'll ask Peter Zentai (@PeterAronZentai) and Alexis Shirtliff (@dcsl-alexis ) about their opinion on this topic, just in case there are limitations we don't know.

2023-01-10 14:50 UTC, inigomarquinez commented on meetings/2023-01-10.md
> +  - Centralize and alert about the dependencies
using [dependencytrack](https://dependencytrack.org/)?

2023-01-11 07:53 UTC, UlisesGascon commented on meetings/2023-01-10.md
> +* Íñigo Marquínez Prado: @inigomarquinez
Added in [734fa8c](https://github.com/onebeyond/admin/pull/19/commits/734fa8c59daf2d7d000b90f7c6a7c7897dce70b6)

2023-01-11 07:53 UTC, UlisesGascon commented on meetings/2023-01-10.md
> +  - Centralize and alert about the dependencies
Added in [734fa8c](https://github.com/onebeyond/admin/pull/19/commits/734fa8c59daf2d7d000b90f7c6a7c7897dce70b6)

2023-01-13 09:33 UTC, UlisesGascon commented on meetings/2023-01-10.md
> +- We will continue working to get a separate slack for open source (lead by Iñigo)
Solved in #23 🎉

2023-01-13 09:41 UTC, inigomarquinez approved these changes

2023-01-13 10:08 UTC, merged