docs: added basic Slack documentation
onebeyond/admin pull request #23
Opened 2023-01-12 13:58 UTC by UlisesGascon

2023-01-12 17:17 UTC, inigomarquinez requested changes
Some suggestions added

2023-01-12 17:17 UTC, inigomarquinez commented on how-to/manage-slack.md
> +Right now the slack is use to improve the communication between the maintainers. If you need access please create an issue in this repo
```suggestion
Right now, slack is used to improve the communication between the maintainers. If you need access, please create an issue in this repo.
```

Apart from the suggestion, the link to the repo is missing.

2023-01-12 17:17 UTC, inigomarquinez commented on how-to/manage-slack.md
> +- `#03-ask-anything`: Great if you are lost
What happens with `02`? 🤔

2023-01-12 17:17 UTC, inigomarquinez commented on how-to/manage-slack.md
> +As well there are some private channels like `#moderation`, `#admins`, etc..
Should we divide them in bullet points, similar to the public ones, and add a brief description?

2023-01-13 09:29 UTC, UlisesGascon commented on how-to/manage-slack.md
> +- `#03-ask-anything`: Great if you are lost
Great catch! Solved by adding `#02-random` in [2d85221](https://github.com/onebeyond/admin/pull/23/commits/2d85221b3d40fc072d9315164f82d3dfa088f407)

2023-01-13 09:30 UTC, UlisesGascon commented on how-to/manage-slack.md
> +As well there are some private channels like `#moderation`, `#admins`, etc..
Refactored in [2d85221](https://github.com/onebeyond/admin/pull/23/commits/2d85221b3d40fc072d9315164f82d3dfa088f407)

2023-01-13 09:50 UTC, inigomarquinez approved these changes
Looks great!

2023-01-13 10:08 UTC, merged